server {
    listen      80;
    listen      [::]:80;
    server_name localhost;
    root        /usr/share/nginx/html;

    # security
#    include     nginxconfig.io/security.conf;

    # index.html fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    # reverse proxy
    location /api/ {
        proxy_pass http://ocelotapigw/api/;
        include    nginxconfig.io/proxy.conf;
    }

    location /connect/ {
        proxy_pass http://ocelotapigw/connect/;
        include    nginxconfig.io/proxy.conf;
    }

    location /xem-ket-qua {
        proxy_pass http://ocelotapigw/api/fr/v1/result/;
        include    nginxconfig.io/proxy.conf;
    }

    location /.well-known/ {
        proxy_pass http://ocelotapigw/.well-known/;
        include    nginxconfig.io/proxy.conf;
    }

    location /Authorize/Protection/ {
        proxy_pass http://ocelotapigw/Authorize/Protection/;
        include    nginxconfig.io/proxy.conf;
    }

    location ~ ^/api/fr/v1/Reports/WebReportDesigner.*\.(js|css|png|svg|eot|otf|ttf|woff|woff2)$ {
             proxy_pass http://ocelotapigw;
    }

    location ~ ^/api/fr/v1/reports/static/images/.*\.(jpg|jpeg|png|svg|css)$ {
             proxy_pass http://ocelotapigw;
    }

    location ~ ^/api/fr/v1/reports/reports/.*\.(frx)$ {
             proxy_pass http://ocelotapigw;
    }

    location ~ ^/api/fr/v1/reports/static/css/.*\.(css|js)$ {
             proxy_pass http://ocelotapigw;
    }

    location ~ ^/api/rm/css/.*\.(js|css|png|svg|eot|otf|ttf|woff|woff2)$ {
             proxy_pass http://ocelotapigw;                                                   
    }

    location ~ ^/api/rm/_blazor.*$ {
             proxy_pass http://ocelotapigw;                 
    }

    location ~ ^/api/rm/_framework/.*\.(js)$ {
             proxy_pass http://ocelotapigw;                 
    }

    location ~ ^/api/ms/v1/static/images.*\.(jpg|jpeg|png|svg|css)$ {
             proxy_pass http://ocelotapigw;
    }

    location ~ ^/api/ms/v1/images.*\.(jpg|jpeg|png|svg)$ {
             proxy_pass http://ocelotapigw;
    }

    location ~ ^/api/la/v1/FilePathology.*\.(jpg|jpeg|png|svg|JPG|JPEG|PNG|SVG)$ {
             proxy_pass http://ocelotapigw;
    }

    # additional config
    include nginxconfig.io/general.conf;
}
